name: Unit Tests

on: push

jobs:
  lint:
    name: Jest Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Yarn Dependencies
      run: yarn install --pure-lockfile

    - name: Run Tests
      run: yarn test
